version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - yii_network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: yii_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yii
      MYSQL_PASSWORD: yii123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yii_network

volumes:
  mysql_data:

networks:
  yii_network:
